export const errorValidation = (errors:any, touched: any) => ({
  name: errors.name && touched.name,
  description: errors.description && touched.description,
  password: errors.password && touched.password,
  width: errors.width && touched.width,
  height: errors.height && touched.height,
  pageDurationMin: errors.pageDurationMin && touched.pageDurationMin,
  pageDurationMax: errors.pageDurationMax && touched.pageDurationMax,
  login: errors.login && touched.login,
  email: errors.email && touched.email,
  firstName: errors.firstName && touched.firstName,
  lastName: errors.lastName && touched.lastName,
  middleName: errors.middleName && touched.middleName,
  code: errors.code && touched.code,
  testValue: errors.testValue && touched.testValue,
  type: errors.type && touched.type,
  lifeTime: errors.lifeTime && touched.lifeTime,
  fontSize: errors.fontSize && touched.fontSize,
  fontId: errors.fontId && touched.fontId,
  alignment: errors.alignment && touched.alignment,
  lineHeight: errors.lineHeight && touched.lineHeight,
  message: errors.message && touched.message,
  configurationId: errors.configurationId && touched.configurationId
})
